Contract metadata
curaOS/contracts pull request #102
Opened 2022-03-04 10:07 UTC by achrafismyname

2022-03-04 12:21 UTC, AshenI99 approved these changes

2022-03-07 15:11 UTC, devey commented on as/cNFT/assembly/models/persistent_nft_contract_metadata.ts
> +    packages_script: Map<string, Map<string, string>> | null
Also, it's better to have typed `string` parameters in this case, so the structure is more explicit.

2022-03-07 15:18 UTC, devey approved these changes

2022-03-24 15:03 UTC, AshenI99 commented on as/cNFT/assembly/models/persistent_nft_contract_metadata.ts
> +    packages_script: Map<string, Map<string, string>> | null
@devey  Seems like `null` with `Map` is valid. Maybe it seems like null cannot be used only with primitive data types.

2022-03-28 09:46 UTC, devey requested changes
I don't want to add too much overhead now, so let's keep `packages_script` as string.

2022-03-28 09:46 UTC, devey commented on tests/cNFT.js
> +    packages_script: {
let's just abort this, let's keep it as it was, simply the string

2022-03-28 10:36 UTC, devey approved these changes
THANKS

2022-03-28 10:41 UTC, merged