Security checks
curaOS/contracts pull request #57
Opened 2022-01-21 22:35 UTC by 0x5CE

- security checks in nft_transfer
- security checks in royalty_payout and bid
- fixed compilation issues

2022-01-25 03:49 UTC, achrafismyname commented on as/cNFT/assembly/core.ts
> +import { assert_one_yocto } from '../../NFT/assembly/asserts'
wrong import here

2022-01-25 03:54 UTC, achrafismyname approved these changes
Seems good :)

2022-02-10 11:13 UTC, devey requested changes
Great, it's coming together! :) I just left a few minor comments, then we can merge it!

2022-02-10 11:59 UTC, AshenI99 approved these changes
Seems good for me other than the things that Yassine mentioned. 👍

2022-02-10 14:43 UTC, devey approved these changes
Good to merge

2022-02-10 14:48 UTC, merged