Implementing market methods
curaOS/contracts pull request #61
Opened 2022-01-24 10:42 UTC by achrafismyname

closes #52 
closes #53 
closes #51

2022-01-26 16:11 UTC, devey requested changes
Thanks for adding these function. Main thing is the need to clean up bidshares (can't coexist with royalty, too much confusion). I will try to finish this PR and look into integrating bidshares into royalty which is only thing missing here.

2022-01-26 16:11 UTC, devey commented on as/cNFT/assembly/models/market.ts
> +export class Ask {
No Asks for now in cNFT, planning on deploying it to mainnet. This would just add complexity right now.

2022-01-26 16:11 UTC, devey commented on as/cNFT/assembly/models/persistent_market.ts
> +    private _askmap: PersistentUnorderedMap<TokenId, Ask>
Remove :)

2022-01-26 16:11 UTC, devey commented on as/cNFT/assembly/models/persistent_market.ts
> +    private _shmap: PersistentUnorderedMap<TokenId, BidShares>
Bid shares need to be part of royalties/payout

2022-01-26 16:11 UTC, devey commented on as/cNFT/assembly/models/persistent_market.ts
> +     * Ask
No ask for now

2022-01-26 16:11 UTC, devey commented on as/cNFT/assembly/models/persistent_market.ts
> +    set_bid_shares(tokenId: TokenId, bidShares: BidShares): void {
need to be integrated into royalty structure, not here

2022-01-26 16:11 UTC, devey commented on as/cNFT/assembly/models/market.ts
> +export class BidShares {
move this to royalty

2022-01-26 16:11 UTC, devey commented on as/cNFT/assembly/utils/market.ts
> +import { u128 } from 'near-sdk-as'
need to move these two function to royalties utils

2022-01-26 16:11 UTC, devey commented on as/cNFT/assembly/market.ts
> + * Ask
clean these

2022-01-26 16:11 UTC, devey commented on as/cNFT/assembly/market.ts
> + * Bid shares
clean these

2022-01-26 19:13 UTC, 0x5CE commented
Looks fine to me other than the changes that @devey requested.

2022-01-27 04:09 UTC, achrafismyname commented
done :)

2022-02-01 14:36 UTC, devey requested changes
Made a few adjustments, especially using royalty instead of bid_shares. Could you make sure tests pass and review code, especially the bid_approve. Thanks!

2022-02-02 14:47 UTC, merged