Added cNFT docs
curaOS/contracts pull request #80
Opened 2022-02-15 12:48 UTC by AshenI99

2022-02-19 10:34 UTC, achrafismyname commented on as/cNFT/assembly/market.ts
> + * Accept a certain bid that owner would like.
`that owner would like.` is not necessary here
maybe replcae it with `on a particular token`

2022-02-19 10:34 UTC, achrafismyname commented on as/cNFT/assembly/mint.ts
>  export function mint(
add a note about the deposit required

2022-02-19 10:34 UTC, achrafismyname commented on as/cNFT/assembly/models/log.ts
> + * Classes used for capture data from the change methods in the contract when they are executed. The subgraph will capture these data and then saved it in the graph node.
The Event Log is not used only by the subgraph, so I think is better to keep this speaking generally.

2022-02-19 10:34 UTC, achrafismyname commented on as/cNFT/assembly/models/market.ts
> +    /** ID of the token that need to bid */
Should be clearer
`/** ID of the token receiving the bid */`

2022-02-19 10:34 UTC, achrafismyname commented on as/cNFT/assembly/models/persistent_market.ts
> +     * @param tokenId Id of the token that need to remove the bid
add `from` at the end

2022-02-19 10:34 UTC, achrafismyname commented on as/cNFT/assembly/models/persistent_tokens.ts
> +     * Get number of tokens saved in the contract
maybe put `tracked` in place of `saved`

2022-02-19 10:34 UTC, achrafismyname commented on as/cNFT/assembly/core.ts
>  export function burn_design(token_id: TokenId): void {
Maybe add an explanation to what burn_design does exactly, because it's not deleting the token completely

2022-02-19 10:34 UTC, achrafismyname commented on as/cNFT/assembly/models/persistent_tokens.ts
> +     * @param accountId ID of the account that owns the removing token
add `from` to the end of this line

2022-02-19 10:34 UTC, achrafismyname commented on as/cNFT/assembly/models/persistent_tokens_metadata.ts
> +    /** Token issued or minted date and time in Unix epoch milliseconds */
issue not issued 
mint not minted

2022-02-21 13:43 UTC, devey requested changes
Looks fine, there is some grammar errors here and there and We should be more verbose on some parts and less on others that are more straightforward. But it's a good start to have the structure so now when we see something that has to be documented or needs a comment or we want to correct one of the comments we know where to look. 

The things I noticed is that the structure seems to only link to files directly instead of showing a more organised structure of `methods`, `classes` like it happens here: https://secretjs.scrt.network. If you could look a bit into this before merging and try to improve that part, then we are good. Otherwise we'lllook into it in some other moment but it's important cause otherwise it's still overkill to navigate the docs.
Some links that i pinned down while looking into this:
(1) https://github.com/scrtlabs/secret.js
(2) https://typedoc.org/guides/options/
(3) https://github.com/christopherthielen/typedoc-plugin-external-module-name
(4) https://github.com/TypeStrong/typedoc/issues/551

I mean, do what you can. I understand this is an `AssemblyScript` project so it might even not be possible or require too much work.

2022-02-21 13:49 UTC, devey commented
Actually this is even better as reference cause it's documentation for a NEAR NFT: https://tenk-dao.github.io/tenk/

2022-02-21 16:52 UTC, merged